# Generated by Django 5.2.17 on 2026-09-25 06:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=9, unique=True)),
                ('player_name', models.CharField(max_length=64)),
                ('player_steam', models.CharField(blank=True, max_length=100, verbose_name='Steam profile / ID')),
                ('player_discord', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('CONNECTED', 'Connected'), ('SCANNING', 'Scanning'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='WAITING', max_length=10)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('client', models.JSONField(blank=True, default=dict)),
                ('token_hash', models.CharField(blank=True, max_length=64)),
                ('scan_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('progress_done', models.PositiveIntegerField(default=0)),
                ('progress_total', models.PositiveIntegerField(default=0)),
                ('progress_module', models.CharField(blank=True, max_length=64)),
                ('live_counts', models.JSONField(blank=True, default=dict)),
                ('interruptions', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('report_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, db_index=True, max_length=12)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('verification_code', models.CharField(blank=True, max_length=12)),
                ('client_check_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('trust', models.CharField(blank=True, max_length=4)),
                ('decision', models.CharField(blank=True, choices=[('', 'Not decided'), ('CLEARED', 'Cleared — no cheats'), ('BANNED', 'Banned'), ('REVIEW', 'Needs another review'), ('RECHECK', 'Re-check required')], db_index=True, max_length=8)),
                ('decision_note', models.CharField(blank=True, max_length=1000)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('notify_state', models.CharField(blank=True, max_length=8)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_sessions', to=settings.AUTH_USER_MODEL)),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='report', serialize=False, to='checks.checksession')),
                ('raw_gzip', models.BinaryField()),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveIntegerField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.JSONField(default=dict)),
                ('modules', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TrustedBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', '64 lowercase hex characters')])),
                ('label', models.CharField(max_length=80)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='FindingRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveIntegerField()),
                ('severity', models.CharField(db_index=True, max_length=8)),
                ('category', models.CharField(max_length=24)),
                ('module', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=300)),
                ('detail', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('weight', models.IntegerField(default=0)),
                ('when', models.CharField(blank=True, max_length=40)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='checks.checksession')),
            ],
            options={
                'ordering': ['idx'],
                'indexes': [models.Index(fields=['session', 'idx'], name='checks_find_session_f33105_idx')],
            },
        ),
    ]
