# Generated by Django 5.2.17 on 2026-09-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='findingrow',
            name='weight',
        ),
        migrations.AddField(
            model_name='findingrow',
            name='kind',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='findingrow',
            name='rule_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='checksession',
            name='verdict',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
