# Generated by Django 5.2.17 on 2026-09-28 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_evidence_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checksession',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, help_text='Not a real player: shown with a TEST label and left out of statistics.', verbose_name='Test run'),
        ),
        migrations.AddField(
            model_name='checksession',
            name='player_token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(max_length=4000)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('decision_at_filing', models.CharField(blank=True, max_length=8)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UPHELD', 'Decision upheld'), ('OVERTURNED', 'Overturned — cleared'), ('RECHECK', 'Re-check ordered')], db_index=True, default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=2000)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='checks.checksession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_label', models.CharField(max_length=120)),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DONE', 'Deleted'), ('REFUSED', 'Refused (kept, with reason)')], db_index=True, default='OPEN', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_requests', to='checks.checksession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
