# Generated by Django 5.2.17 on 2026-09-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0003_player_appeals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Under review'), ('UPHELD', 'Decision upheld'), ('OVERTURNED', 'Overturned — cleared'), ('RECHECK', 'Re-check ordered')], db_index=True, default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='checksession',
            name='decision',
            field=models.CharField(blank=True, choices=[('', 'Not decided'), ('CLEARED', 'Clean'), ('BANNED', 'Ban'), ('REVIEW', 'Needs a second look'), ('RECHECK', 'Re-check')], db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='checksession',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, help_text='Not a real player: shown with a TEST label and left out of statistics.', verbose_name='Test check'),
        ),
        migrations.AlterField(
            model_name='checksession',
            name='player_steam',
            field=models.CharField(blank=True, max_length=100, verbose_name='Steam (link or ID)'),
        ),
        migrations.AlterField(
            model_name='checksession',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting for the player'), ('CONNECTED', 'Checker connected'), ('SCANNING', 'Checking'), ('COMPLETED', 'Done'), ('ABANDONED', 'Checker lost'), ('EXPIRED', 'Code expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='WAITING', max_length=10),
        ),
    ]
