# Generated by Django 5.2.17 on 2026-09-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0004_translatable_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='checksession',
            name='client_outcome',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='checksession',
            name='protocol',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checksession',
            name='upload_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checksession',
            name='upload_nonce_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
