# Generated by Django 5.2.17 on 2026-09-25 06:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ttl_minutes', models.PositiveIntegerField(default=30, help_text='How long a check code stays valid before the player enters it.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('heartbeat_timeout_minutes', models.PositiveIntegerField(default=4, help_text='A running check that stops reporting for this long is marked ABANDONED.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(60)])),
                ('retention_days', models.PositiveIntegerField(default=180, help_text='Completed checks older than this are deleted automatically (0 = keep forever).', validators=[django.core.validators.MaxValueValidator(3650)])),
                ('require_2fa', models.BooleanField(default=True, help_text='Every team member must enable two-factor authentication.')),
                ('min_checker_version', models.CharField(default='1.0.0', help_text='Older checkers are refused when they try to connect.', max_length=20, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+){0,3}$')])),
                ('block_untrusted_builds', models.BooleanField(default=False, help_text='Refuse to connect checkers whose file hash is not in the trusted build list.')),
                ('fast_scan_seconds', models.PositiveIntegerField(default=20, help_text='A completed scan faster than this (measured by the server) is flagged.', validators=[django.core.validators.MaxValueValidator(3600)])),
            ],
            options={
                'verbose_name': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_label', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('target', models.CharField(blank=True, max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at', '-id'],
            },
        ),
    ]
