# Generated by Django 5.2.17 on 2026-09-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='accept_unbound_reports',
            field=models.BooleanField(default=False, help_text='Transition only: accept reports from checkers older than 1.3, which cannot bind their report to the check. Such reports are marked and have weaker replay protection.'),
        ),
    ]
