# Generated by Django 5.2.17 on 2026-09-25 06:44

import accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('rank', models.PositiveSmallIntegerField(help_text='Higher rank manages lower ranks. Owner is 100.')),
                ('color', models.CharField(default='#6f78ef', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')])),
                ('description', models.CharField(blank=True, max_length=200)),
                ('permissions', models.JSONField(default=list)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-rank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9_.-]{2,31}$', '3-32 characters: lowercase letters, digits, dot, dash or underscore; must start with a letter or digit.')], verbose_name='alias')),
                ('display_name', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('discord', models.CharField(blank=True, help_text='Discord name, shown to teammates.', max_length=64)),
                ('discord_webhook', models.CharField(blank=True, help_text='Optional: completed checks are posted to this Discord channel webhook.', max_length=300, validators=[django.core.validators.RegexValidator('^https://(?:(?:ptb|canary)\\.)?discord(?:app)?\\.com/api/webhooks/\\d{5,25}/[A-Za-z0-9_-]{20,120}$', 'Must be a Discord webhook URL (https://discord.com/api/webhooks/...).')])),
                ('totp_secret', models.CharField(blank=True, max_length=64)),
                ('totp_enabled', models.BooleanField(default=False)),
                ('totp_last_step', models.BigIntegerField(default=0)),
                ('must_change_password', models.BooleanField(default=False)),
                ('session_epoch', models.PositiveIntegerField(default=0)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='accounts.role')),
            ],
            options={
                'ordering': ['username'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('invite', 'Invite'), ('reset', 'Password reset')], max_length=10)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
